version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
      exclude: [manic-systems/*]
    groups:
      actions:
        patterns: ["*"]
    commit-message:
      prefix: ci
  - package-ecosystem: nix
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    commit-message:
      prefix: flake
