name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            archive: watchdog-linux-amd64
          - target: aarch64-unknown-linux-gnu
            archive: watchdog-linux-arm64
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Rust
        env:
          TARGET: ${{ matrix.target }}
        run: rustup update stable --no-self-update && rustup target add "$TARGET"

      - name: Build
        uses: houseabsolute/actions-rust-cross@21b0f18dc621b25bfae556ff2791fca4173121e8 # v1.0.8
        env:
          WATCHDOG_COMMIT: ${{ github.sha }}
          WATCHDOG_BUILD_DATE: ${{ github.event.repository.updated_at }}
        with:
          command: build
          target: ${{ matrix.target }}
          args: "--locked --release"
          strip: true

      - name: Create artifact
        run: |
          cp target/${{ matrix.target }}/release/watchdog ${{ matrix.archive }}
          tar -czvf ${{ matrix.archive }}.tar.gz ${{ matrix.archive }}

      - name: Upload artifact
        uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
        with:
          name: ${{ matrix.archive }}
          path: ${{ matrix.archive }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@9000827ccba6bdab643e8b6fd33ac0654aef8333 # v8.0.2
        with:
          path: artifacts
          pattern: watchdog-*
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.6.2 # zizmor: ignore[superfluous-actions]
        with:
          files: artifacts/watchdog-*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
